### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by UDPSendToFailed** [lsswizard/smt590_kernel#1]
Hi!

Just found your repo, I have the same device, running on the stock kernel with RROS GSI. Is this kernel ready to use or WIP? Any performance updates compared to the stock one?

**Comment by UDPSendToFailed** [comment]
Well, it doesn't compile for me, guess I'll have to wait for the official release

![image](https://user-images.githubusercontent.com/16057404/138491259-68266463-b309-4852-921f-eb331c1b3d25.png)

**Comment by lsswizard** [comment]
it compiles fine now, its working for me on treble roms, plenty of updates, use  smartpack kernel manager from play store and see.

**Comment by UDPSendToFailed** [comment]
Thanks a lot for your work! :) Just installed it and got ~200 MB more free RAM compared to the stock kernel. 

I see it has voltage controls enabled for the CPU, have you tried overclocking? I gave it a try before, changed the speed bins in the sdm450 .dts files to run the CPU on the level of Snapdragon 625 / 626 which are basically the same as 450, but higher clock speeds. 
Got it "working", the increased clock speeds showed up everywhere, I was able to select them in kernel manager, the CPU was running on 2.2 GHz, but the performance didn't increase even a little bit.
Here is my Geekbench result on 2.2 GHz, performance is the same as on 1.8 GHz: https://browser.geekbench.com/v5/cpu/6094576
Did I miss something when modifying the .dts files?

Edit: WiFi connection became really unstable, basically the internet access dies in a few minutes with lots of errors in logcat, otherwise the kernel works fine. I don't know if this matters or not, but the WiFi MAC address of my tablet has changed after flashing this kernel, it reverts back to normal if I flash stock.

![Screenshot_20211023-225336316](https://user-images.githubusercontent.com/16057404/138571284-1fccb133-be9e-44d0-b333-88968cffdde3.jpg)

**Comment by lsswizard** [comment]
I've tried overclocking , no joy yet as you said no improvement when you benchmark, its more than just the dts files, samsung changed a lot of things

as for the wifii, probably last merge i did which is updated the drivers for the internet.

Enabled colour change to, check screen in the app, increase saturation for better colour

check here for example of overclock,    [](url)https://github.com/nexus-projects/nexus_kernel_motorola_sanders/commit/bdd3af5cdc7c1d45d8b18c5294b87a1f3cddb1d7

dont edit that dts, just our samsung one.

**Comment by UDPSendToFailed** [comment]
Yea, did the same as mentioned commit, without success. 
I want to improve the device's usability by porting a newer TWRP / OrangeFox to it which supports encryption (the current one from XDA can't unlock FDE), get Android 12 running, some CPU / GPU OC, make a working GSI overlay to fix automatic brightness, etc. 
But I have no idea where to start, I'm new to Android modding. Tried porting OrangeFox once, ended up like this, almost bricking the device: https://github.com/SebaUbuntu/TWRP-device-tree-generator/issues/40
So I guess I'll need to research a lot. :D

**Comment by lsswizard** [comment]
i have compiled it, not got encryption to work, i  also compiled shrp, its on my repositories here and it works with out encryption.

by the way , wait for battery to run out if it loops, then hold all three buttons and insert usb,  which should be connected to the computer, and download mode will appear and flash original firmware to fix using odin.

**Comment by lsswizard** [comment]
i think the problem for the wifi is the kud merges, may have to rebase and remove will see.

**Comment by UDPSendToFailed** [comment]
I may give it a try again, but it's hard to test recoveries while having to wait hours for the battery. :/ BTW, is your kernel able to run 64-bit GSIs? I had to compile it with arch=arm64 instead of arch=arm for stock, I don't know if this changes anything.

**Comment by lsswizard** [comment]
kernel is 64bit, its the vendor that needs updating i believe, because of 32bit libs etc.

My shrp recovery works a treat for me, my orangefox works but haven't updated it  much, but they all use twrp device, just extra flags

i'll attach my shrp recovery.

[recovery.tar.zip](https://github.com/lsswizard/sm-t590_kernel_caf/files/7413746/recovery.tar.zip)

**Comment by lsswizard** [comment]
[SHRP_AddonRescue_v3.1_gta2xlwifi-1634657489.zip](https://github.com/lsswizard/sm-t590_kernel_caf/files/7413749/SHRP_AddonRescue_v3.1_gta2xlwifi-1634657489.zip)

for addon extras after u install recovery.

**Comment by UDPSendToFailed** [comment]
Thanks a lot, flashed it, working fine! :)

**Comment by UDPSendToFailed** [comment]
Hi @lsswizard!

**Edit: Seems to be fixed with setting CONFIG_SOFT_WATCHDOG=n in defconfig**

I successfully managed to run LineageOS 18.1 64-bit on SM-T590 with your kernel and some modifications to the vendor partition. However with LineageOS 19.1 (or any other Android 12-based GSI) I get freezes and kernel panics due to watchdog timeout. 

Do you have any idea about what could cause this? It would be nice to have an usable 64-bit Android 12 ROM for our device. Thanks in advance!

[logcat.txt](https://github.com/lsswizard/sm-t590_kernel_caf/files/8411301/logcat.txt)
[last_kmsg.txt](https://github.com/lsswizard/sm-t590_kernel_caf/files/8411304/last_kmsg.txt)


```<2>[  110.560127] I[6:      swapper/6:    0] softdog: Initiating panic
<0>[  110.560296] I[6:      swapper/6:    0] Kernel panic - not syncing: Software Watchdog Timer expired
<6>[  110.560425] I[6:      swapper/6:    0] CPU: 6 PID: 0 Comm: swapper/6 Tainted: G        W      3.18.140Slayer #5
<6>[  110.560531] I[6:      swapper/6:    0] Hardware name: Samsung Tab A2 XL WIFI EUR OPEN Rev04 (DT)
<0>[  110.560625] I[6:      swapper/6:    0] Call trace:
<6>[  110.560697] I[6:      swapper/6:    0] [<ffffffc00008bec4>] dump_backtrace+0x0/0x128
<6>[  110.560785] I[6:      swapper/6:    0] [<ffffffc00008c000>] show_stack+0x14/0x1c
<6>[  110.560878] I[6:      swapper/6:    0] [<ffffffc00124b3f4>] dump_stack+0x84/0xa8
<6>[  110.560982] I[6:      swapper/6:    0] [<ffffffc001249b88>] panic+0x1a4/0x388
<6>[  110.561085] I[6:      swapper/6:    0] [<ffffffc000aa40c4>] dm_send_uevents+0x0/0x170
<6>[  110.561188] I[6:      swapper/6:    0] [<ffffffc00011eeec>] call_timer_fn+0x4c/0x1c4
<6>[  110.561285] I[6:      swapper/6:    0] [<ffffffc00011fc5c>] run_timer_softirq+0x294/0x61c
<6>[  110.561390] I[6:      swapper/6:    0] [<ffffffc0000b3134>] __do_softirq+0x104/0x3fc
<6>[  110.561483] I[6:      swapper/6:    0] [<ffffffc0000b3700>] irq_exit+0x9c/0xcc
<6>[  110.561575] I[6:      swapper/6:    0] [<ffffffc00010cdf4>] __handle_domain_irq+0x78/0xc8
<6>[  110.561668] I[6:      swapper/6:    0] [<ffffffc0000828a0>] gic_handle_irq+0x4c/0xa8
<6>[  110.561761] I[6:      swapper/6:    0] Exception stack(0xffffffc0ae2fbcf0 to 0xffffffc0ae2fbe20)
<6>[  110.561866] I[6:      swapper/6:    0] bce0:                                     00000000 00000000 00000000 00000080
<6>[  110.561991] I[6:      swapper/6:    0] bd00: 421f9000 00000000 00ad9bb4 ffffffc0 60400145 00000000 ffffffe0 00000000
<6>[  110.562128] I[6:      swapper/6:    0] bd20: 00b42eb6 00000000 000003e8 00000000 34155555 00000000 0000a33e 00000000
<6>[  110.562251] I[6:      swapper/6:    0] bd40: 00000018 00000000 a1b42400 001d8119 82eb19b5 00000000 6b63482c 65762764
<6>[  110.562375] I[6:      swapper/6:    0] bd60: 7f7f7f7f 7f7f7f7f a8ff2868 fefefebf ff7f7f7f ffffffff 01010101 01010101
<6>[  110.562485] I[6:      swapper/6:    0] bd80: 00000010 00000000 00000038 00000000 ffffffff 0fffffff 00000400 00000000
<6>[  110.562593] I[6:      swapper/6:    0] bda0: 001b8a00 00000000 00000466 00000000 0000000e 00000000 00000000 00000000
<6>[  110.562702] I[6:      swapper/6:    0] bdc0: 00002e20 00000000 001685d6 00000000 01c527f8 ffffffc0 af9e9378 ffffffc0
<6>[  110.562811] I[6:      swapper/6:    0] bde0: 000001b6 00000000 aa36cc18 ffffffc0 00000001 00000000 01ba0ab8 ffffffc0
<6>[  110.562937] I[6:      swapper/6:    0] be00: bde3c2d1 00000019 ae2fbe50 ffffffc0 00ad9b90 ffffffc0 ae2fbe50 ffffffc0
<6>[  110.563065] I[6:      swapper/6:    0] [<ffffffc0000861b4>] el1_irq+0xb4/0x158
<6>[  110.563162] I[6:      swapper/6:    0] [<ffffffc000ad4230>] cpuidle_enter_state+0x80/0x260
<6>[  110.563252] I[6:      swapper/6:    0] [<ffffffc000ad4658>] cpuidle_enter+0x18/0x20
<6>[  110.563341] I[6:      swapper/6:    0] [<ffffffc0000fc434>] cpu_startup_entry+0x320/0x38c
<6>[  110.563442] I[6:      swapper/6:    0] [<ffffffc000090ef4>] secondary_start_kernel+0xf8/0x11c
<2>[  110.563577] I[4:     logd.klogd:  453] CPU4: stopping
<6>[  110.563646] I[4:     logd.klogd:  453] 
<6>[  110.563708] I[4:     logd.klogd:  453] CPU: 4 PID: 453 Comm: logd.klogd Tainted: G        W      3.18.140Slayer #5
<6>[  110.563821] I[4:     logd.klogd:  453] Hardware name: Samsung Tab A2 XL WIFI EUR OPEN Rev04 (DT)
<6>[  110.563924] I[4:     logd.klogd:  453] task: ffffffc0a812c100 ti: ffffffc0a800c000 task.ti: ffffffc0a800c000
<6>[  110.564036] I[4:     logd.klogd:  453] PC is at 0x7e1035c0a4
<6>[  110.564109] I[4:     logd.klogd:  453] LR is at 0x7e1035f174
<6>[  110.564182] I[4:     logd.klogd:  453] pc : [<0000007e1035c0a4>] lr : [<0000007e1035f174>] pstate: 80000000
<6>[  110.564290] I[4:     logd.klogd:  453] sp : 0000007b7bd2f490
<6>[  110.564363] I[4:     logd.klogd:  453] x29: 0000007b7bd2f4b0 x28: 0000000000000001 
<6>[  110.564463] I[4:     logd.klogd:  453] x27: 0000000000007fff x26: 7fffffffffffffff 
<6>[  110.564559] I[4:     logd.klogd:  453] x25: ffffffffffffffff x24: 0000007b7bd31000 
<6>[  110.564655] I[4:     logd.klogd:  453] x23: 0000000000003fff x22: 0000007b7bd31000 
<6>[  110.564750] I[4:     logd.klogd:  453] x21: 0000007b7bd2f560 x20: 0000000000000001 
<6>[  110.564846] I[4:     logd.klogd:  453] x19: 0000007d5f033010 x18: 0000007b7b036000 
<6>[  110.564941] I[4:     logd.klogd:  453] x17: 0000000000000006 x16: 0000000000000000 
<6>[  110.565037] I[4:     logd.klogd:  453] x15: 0000000000000006 x14: 0000000000000004 
<6>[  110.565132] I[4:     logd.klogd:  453] x13: 0000000000000002 x12: 0000007e102e320c 
<6>[  110.565226] I[4:     logd.klogd:  453] x11: 0000000000000000 x10: 0000000000000000 
<6>[  110.565320] I[4:     logd.klogd:  453] x9 : 0000000000000000 x8 : 0000000000000000 
<6>[  110.565416] I[4:     logd.klogd:  453] x7 : 00000000c28f5c29 x6 : 0000000080000000 
<6>[  110.565511] I[4:     logd.klogd:  453] x5 : fffffffffffffe93 x4 : 0000000051eb851f 
<6>[  110.565607] I[4:     logd.klogd:  453] x3 : 0000007b7bd2f560 x2 : 0000000000000001 
<6>[  110.565702] I[4:     logd.klogd:  453] x1 : 0000007b7bd2f5e0 x0 : 0000007d5f033010 
<6>[  110.565796] I[4:     logd.klogd:  453] 
<6>[  110.565855] I[4:     logd.klogd:  453] CPU: 4 PID: 453 Comm: logd.klogd Tainted: G        W      3.18.140Slayer #5
<6>[  110.565969] I[4:     logd.klogd:  453] Hardware name: Samsung Tab A2 XL WIFI EUR OPEN Rev04 (DT)
<0>[  110.566068] I[4:     logd.klogd:  453] Call trace:
<6>[  110.566139] I[4:     logd.klogd:  453] [<ffffffc00008bec4>] dump_backtrace+0x0/0x128
<6>[  110.566235] I[4:     logd.klogd:  453] [<ffffffc00008c000>] show_stack+0x14/0x1c
<6>[  110.566329] I[4:     logd.klogd:  453] [<ffffffc00124b3f4>] dump_stack+0x84/0xa8
<6>[  110.566420] I[4:     logd.klogd:  453] [<ffffffc000091798>] handle_IPI+0x334/0x4c8
<6>[  110.566512] I[4:     logd.klogd:  453] [<ffffffc0000828f8>] gic_handle_irq+0xa4/0xa8
<6>[  110.566604] I[4:     logd.klogd:  453] Exception stack(0xffffffc0a800fe90 to 0xffffffc0a800ffc0)```
